#parser.add_argument("--emb_epochs", default=5, type=int)
#parser.add_argument("--sup_epochs", default=5, type=int)
#parser.add_argument("--gan_epochs", default=600, type=int)
#parser.add_argument("--batch_size", default=128, type=int)
#parser.add_argument("--hidden_dim", default=20, type=int)
#parser.add_argument("--num_layers", default=3, type=int)
#parser.add_argument("--dis_thresh", default=0.05, type=float)  # default 0.15
#parser.add_argument("--optimizer", choices=["adam"], default="adam", type=str)
#parser.add_argument("--learning_rate", default=1e-3, type=float)
MODEL:
  emb_epochs: 600
  sup_epochs: 600
  batch_size: 128
  hidden_dim: 20
  num_layers: 3
  dis_thresh: 0.05
  learning_rate: 1e-3
DATA:
  max_seq_len: 100
  train_rate: 0.5
DOGAN:
  max_loop: 10

